const RESPONSE_OK = 200;
const RESPONSE_OK_CREATED = 201;
const NOT_FOUND_ERROR = 404;
const INTERNAL_ERROR = 500;
const BAD_REQUEST_ERROR = 400;

module.exports = {
  RESPONSE_OK,
  RESPONSE_OK_CREATED,
  NOT_FOUND_ERROR,
  INTERNAL_ERROR,
  BAD_REQUEST_ERROR
};
